# Generated by Django 4.0.2 on 2022-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variacao',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_maximo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_minimo',
            field=models.FloatField(),
        ),
    ]
