# Generated by Django 4.0.2 on 2022-02-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_variation_variacao_alter_produto_preco_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('C', 'Casacos'), ('M', 'Moletons'), ('B', 'Blusas'), ('A', 'Calças')], default='', max_length=1),
        ),
    ]
